package org.mockserver.netty.integration.tls.inbound;

import org.junit.Test;
import org.mockserver.echo.http.EchoServer;
import org.mockserver.netty.MockServer;
import org.mockserver.streams.IOStreamUtils;

import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLEngine;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.Socket;
import java.net.SocketTimeoutException;
import java.nio.ByteBuffer;
import java.util.concurrent.TimeUnit;

import static java.nio.charset.StandardCharsets.UTF_8;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.greaterThanOrEqualTo;
import static org.hamcrest.Matchers.lessThan;
import static org.mockserver.configuration.Configuration.configuration;
import static org.mockserver.stop.Stop.stopQuietly;
import static org.mockserver.test.Assert.assertContains;

/**
 * Proves that an inbound (server-side) TLS handshake MockServer terminates is bounded by the configured
 * connection timeout ({@code socketConnectionTimeoutInMillis}) rather than by Netty's fixed default
 * {@code SslHandler} handshake timeout of 10,000ms. Covers both inbound termination sites:
 * <ul>
 *   <li>the port-unification / direct-HTTPS path ({@code SniHandler}); and</li>
 *   <li>the CONNECT MITM path ({@code RelayConnectHandler}), where MockServer terminates the tunnelled TLS.</li>
 * </ul>
 * <p>
 * The mechanism is exercised deterministically (no reliance on machine load): a raw client {@link Socket}
 * sends a genuine TLS ClientHello (generated by a client {@link SSLEngine}) and then withholds the rest of
 * the handshake forever, so the server's handshake can only be ended by its handshake timeout. With the fix
 * a small configured connection timeout ends it at roughly that bound; both tests double as the negative
 * control - revert the {@code setHandshakeTimeoutMillis} calls in {@code SniHandler} /
 * {@code RelayConnectHandler} and the handshake instead runs to Netty's 10s default, so the client read
 * times out at {@link #READ_CEILING_MILLIS} and the {@code lessThan} timing assertion fails.
 * <p>
 * Uses per-instance {@link org.mockserver.configuration.Configuration} objects only (never the global
 * {@code ConfigurationProperties}), so it mutates no shared state and needs no sequential registration.
 */
public class TlsHandshakeTimeoutIntegrationTest {

    private static final long CONFIGURED_BOUND_MILLIS = 1500L;
    // Ceiling comfortably above the configured bound but well below Netty's fixed 10,000ms default, so a
    // handshake that ran to the default breaches it. Also the client read timeout, so a non-closing server
    // fails the test promptly instead of hanging.
    private static final int READ_CEILING_MILLIS = 6000;

    @Test
    public void shouldBoundDirectInboundTlsHandshakeByConfiguredConnectionTimeout() throws Exception {
        MockServer mockServer = new MockServer(configuration().socketConnectionTimeoutInMillis(CONFIGURED_BOUND_MILLIS), 0);
        try (Socket socket = new Socket("127.0.0.1", mockServer.getLocalPort())) {
            socket.setSoTimeout(READ_CEILING_MILLIS + 2000);

            // send a real ClientHello so port unification detects TLS and installs the server SslHandler, then stall
            socket.getOutputStream().write(clientHello());
            socket.getOutputStream().flush();

            long elapsedMillis = timeUntilServerClosesHandshake(socket);

            assertThat("handshake ended no earlier than the configured connection timeout (proves the timeout drove it)",
                elapsedMillis, greaterThanOrEqualTo(CONFIGURED_BOUND_MILLIS - 300));
            assertThat("handshake was bounded by the configured connection timeout, not Netty's fixed 10,000ms default (elapsed " + elapsedMillis + "ms)",
                elapsedMillis, lessThan((long) READ_CEILING_MILLIS));
        } finally {
            stopQuietly(mockServer);
        }
    }

    /**
     * The ClientHello stage: until the whole ClientHello has arrived and the server certificate is chosen, the
     * handshake is held by {@code SniHandler}, which Netty bounds by a fixed 10 s unless told otherwise. The idle
     * timeout is turned off so it cannot be what ends the connection.
     */
    @Test
    public void shouldBoundAnIncompleteClientHelloByConfiguredConnectionTimeout() throws Exception {
        MockServer mockServer = new MockServer(configuration()
            .socketConnectionTimeoutInMillis(CONFIGURED_BOUND_MILLIS)
            .inboundConnectionIdleTimeoutMillis(0L), 0);
        try (Socket socket = new Socket("127.0.0.1", mockServer.getLocalPort())) {
            socket.setSoTimeout(READ_CEILING_MILLIS);

            // enough of a real ClientHello for port unification to detect TLS, then stall
            byte[] clientHello = clientHello();
            socket.getOutputStream().write(clientHello, 0, clientHello.length / 2);
            socket.getOutputStream().flush();

            long elapsedMillis = timeUntilServerClosesHandshake(socket);

            assertThat("ClientHello stage ended no earlier than the configured connection timeout (proves the timeout drove it)",
                elapsedMillis, greaterThanOrEqualTo(CONFIGURED_BOUND_MILLIS - 300));
            assertThat("ClientHello stage was bounded by the configured connection timeout, not Netty's fixed 10,000ms default (elapsed " + elapsedMillis + "ms)",
                elapsedMillis, lessThan((long) READ_CEILING_MILLIS));
        } finally {
            stopQuietly(mockServer);
        }
    }

    @Test
    public void shouldBoundConnectTunnelInboundTlsHandshakeByConfiguredConnectionTimeout() throws Exception {
        MockServer mockServer = new MockServer(configuration().socketConnectionTimeoutInMillis(CONFIGURED_BOUND_MILLIS), 0);
        EchoServer secureEchoServer = new EchoServer(true);
        try (Socket socket = new Socket("127.0.0.1", mockServer.getLocalPort())) {
            socket.setSoTimeout(READ_CEILING_MILLIS + 2000);
            OutputStream output = socket.getOutputStream();

            // open the CONNECT tunnel
            output.write(("" +
                "CONNECT 127.0.0.1:" + secureEchoServer.getPort() + " HTTP/1.1\r\n" +
                "Host: 127.0.0.1:" + secureEchoServer.getPort() + "\r\n" +
                "\r\n"
            ).getBytes(UTF_8));
            output.flush();
            assertContains(IOStreamUtils.readHttpInputStreamToString(socket), "HTTP/1.1 200 OK");

            // send a real ClientHello into the tunnel so RelayConnectHandler terminates the TLS, then stall
            output.write(clientHello());
            output.flush();

            long elapsedMillis = timeUntilServerClosesHandshake(socket);

            assertThat("tunnelled handshake ended no earlier than the configured connection timeout (proves the timeout drove it)",
                elapsedMillis, greaterThanOrEqualTo(CONFIGURED_BOUND_MILLIS - 300));
            assertThat("tunnelled handshake was bounded by the configured connection timeout, not Netty's fixed 10,000ms default (elapsed " + elapsedMillis + "ms)",
                elapsedMillis, lessThan((long) READ_CEILING_MILLIS));
        } finally {
            stopQuietly(secureEchoServer);
            stopQuietly(mockServer);
        }
    }

    /**
     * Reads and discards whatever the server sends (its ServerHello flight, then a close alert) until the
     * connection closes, returning how long that took. If the read blocks past the socket timeout - which is
     * what happens when the handshake runs to Netty's fixed 10s default rather than the configured bound - it
     * returns the elapsed time so the caller's ceiling assertion fails with a clear message rather than the
     * test throwing.
     */
    private static long timeUntilServerClosesHandshake(Socket socket) throws Exception {
        long startNanos = System.nanoTime();
        InputStream input = socket.getInputStream();
        byte[] buffer = new byte[512];
        try {
            while (input.read(buffer) != -1) {
                // discard the ServerHello flight; keep reading until the server closes the handshake
            }
        } catch (SocketTimeoutException ignore) {
            // server did not close within the socket timeout: elapsed will breach the ceiling assertion
        }
        return TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - startNanos);
    }

    private static byte[] clientHello() throws Exception {
        SSLContext sslContext = SSLContext.getInstance("TLS");
        sslContext.init(null, null, null);
        SSLEngine engine = sslContext.createSSLEngine();
        engine.setUseClientMode(true);
        ByteBuffer applicationData = ByteBuffer.allocate(0);
        ByteBuffer networkData = ByteBuffer.allocate(engine.getSession().getPacketBufferSize());
        engine.wrap(applicationData, networkData);
        networkData.flip();
        byte[] bytes = new byte[networkData.remaining()];
        networkData.get(bytes);
        return bytes;
    }
}
