steps:
  - label: ":pipeline: Generate pipeline"
    command: ".buildkite/scripts/generate-pipeline.sh"
    timeout_in_minutes: 2
    retry:
      automatic:
        - exit_status: -1   # agent lost (e.g. Spot reclamation)
          limit: 2
        - exit_status: 255  # agent forced shutdown
          limit: 2
