{{- if and .Values.app.tls.enabled .Values.app.tls.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "release.name" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ template "chart.name_version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
{{- if .Values.app.tls.certificateAuthorityCertificate }}
  CertificateAuthorityCertificate.pem: |
{{ .Values.app.tls.certificateAuthorityCertificate | indent 4 }}
{{- end }}
{{- if .Values.app.tls.certificateAuthorityPrivateKey }}
  CertificateAuthorityPrivateKey.pem: |
{{ .Values.app.tls.certificateAuthorityPrivateKey | indent 4 }}
{{- end }}
{{- if .Values.app.tls.certificate }}
  Certificate.pem: |
{{ .Values.app.tls.certificate | indent 4 }}
{{- end }}
{{- if .Values.app.tls.privateKey }}
  PrivateKey.pem: |
{{ .Values.app.tls.privateKey | indent 4 }}
{{- end }}
{{- end }}
