package org.mockserver.oidc;

import com.fasterxml.jackson.databind.ObjectWriter;
import org.mockserver.authentication.jwt.JWKGenerator;
import org.mockserver.keys.AsymmetricKeyPair;
import org.mockserver.mock.Expectation;
import org.mockserver.model.HttpClassCallback;
import org.mockserver.serialization.ObjectMapperFactory;

import java.util.ArrayList;
import java.util.List;

import static org.mockserver.model.HttpRequest.request;
import static org.mockserver.model.HttpResponse.response;

/**
 * Generates MockServer {@link Expectation}s that serve a complete set of OIDC/OAuth2
 * identity provider endpoints: discovery, JWKS, token, authorize, userinfo, introspection,
 * revocation, and end-session (logout). Tokens are signed with a key pair (generated by
 * default, or supplied via PEM / JWK) whose public key is exposed via the JWKS endpoint, so
 * OIDC-aware clients can validate tokens end-to-end without any external infrastructure.
 *
 * <p>Tokens are minted at request time by {@link OidcTokenCallback} (so a per-request
 * {@code nonce} from the authorize request can be embedded in the {@code id_token}), not
 * pre-baked at generate time.
 *
 * <p>Usage mirrors the WSDL and OpenAPI importers: call
 * {@link #generate(OidcProviderConfiguration)} with a configuration (or defaults)
 * and upsert the returned expectations into the mock server.
 */
public class OidcProviderGenerator {

    private static final String APPLICATION_JSON = "application/json; charset=utf-8";
    static final String LOGOUT_PATH = "/logout";

    private final ObjectWriter objectWriter = ObjectMapperFactory.createObjectMapper(true, false);

    /**
     * Generates OIDC provider expectations from the given configuration.
     *
     * @param config the provider configuration (must not be null)
     * @return the generated expectations (one per endpoint, never empty)
     */
    public List<Expectation> generate(OidcProviderConfiguration config) {
        if (config == null) {
            throw new IllegalArgumentException("OIDC provider configuration is required");
        }

        // Resolve the signing key pair (generated by default, or supplied via PEM / JWK) for the
        // configured algorithm. The same key both signs tokens (via the minter) and is published at
        // the JWKS endpoint, preserving the sign/publish invariant.
        AsymmetricKeyPair keyPair = OidcKeyProvider.resolveKeyPair(config);
        JWKGenerator jwkGenerator = new JWKGenerator();
        String jwksJson = jwkGenerator.generateJWK(keyPair);

        // Tokens are minted at request time by the OidcTokenCallback (so a per-request nonce can be
        // embedded in the id_token), not pre-baked here.
        OidcTokenMinter tokenMinter = new OidcTokenMinter(config, keyPair);

        List<Expectation> expectations = new ArrayList<>();

        // 1. Discovery document
        expectations.add(buildDiscoveryExpectation());

        // 2. JWKS endpoint
        expectations.add(buildJwksExpectation(config, jwksJson));

        // 3. Token endpoint (also serves the authorization_code grant exchange)
        expectations.add(buildTokenExpectation(config));

        // 4. Authorize endpoint (authorization-code grant)
        expectations.add(buildAuthorizeExpectation(config));

        // 5. Userinfo endpoint
        expectations.add(buildUserinfoExpectation(config));

        // 6. Introspection endpoint
        expectations.add(buildIntrospectionExpectation(config));

        // 7. Revocation endpoint
        expectations.add(buildRevocationExpectation(config));

        // 8. End-session (logout) endpoint
        expectations.add(buildLogoutExpectation());

        // 9. Device-authorization endpoint (RFC 8628)
        expectations.add(buildDeviceAuthorizationExpectation(config));

        // Register provider state so the /authorize, /token, /introspect and /device_authorization
        // callbacks can complete the flows (issue codes, validate PKCE, mint tokens carrying the nonce,
        // poll device codes, resolve opaque tokens).
        OidcAuthorizationStore.getInstance().registerProvider(
            new OidcAuthorizationStore.Provider(
                config.getAuthorizePath(), config.getTokenPath(), config.getDeviceAuthorizationPath(),
                config, tokenMinter
            )
        );

        return expectations;
    }

    private Expectation buildDiscoveryExpectation() {
        // A class callback so the issuer (and every endpoint URL derived from it) is resolved per
        // request from the Host header. OIDC Discovery 4.3 requires the advertised issuer to match the
        // URL the relying party used; a fixed issuer baked in at generate time breaks every client
        // running the mock on a random port.
        return new Expectation(
            request()
                .withMethod("GET")
                .withPath("/.well-known/openid-configuration")
        )
            .withId("oidc.discovery")
            .thenRespond(HttpClassCallback.callback(OidcDiscoveryCallback.class.getName()));
    }

    private Expectation buildJwksExpectation(OidcProviderConfiguration config, String jwksJson) {
        return new Expectation(
            request()
                .withMethod("GET")
                .withPath(config.getJwksPath())
        )
            .withId("oidc.jwks")
            .thenRespond(response()
                .withStatusCode(200)
                .withHeader("content-type", APPLICATION_JSON)
                .withBody(jwksJson));
    }

    private Expectation buildTokenExpectation(OidcProviderConfiguration config) {
        // A class callback so the same /token endpoint serves both the existing grants
        // (client_credentials, refresh_token — minting tokens at request time) and the
        // authorization_code grant (validating the code + PKCE, then minting tokens carrying nonce).
        return new Expectation(
            request()
                .withMethod("POST")
                .withPath(config.getTokenPath())
        )
            .withId("oidc.token")
            .thenRespond(HttpClassCallback.callback(OidcTokenCallback.class.getName()));
    }

    private Expectation buildAuthorizeExpectation(OidcProviderConfiguration config) {
        // A class callback so /authorize can echo the dynamic `state`, mint an authorization
        // `code`, record any PKCE challenge, and 302-redirect back to the redirect_uri.
        return new Expectation(
            request()
                .withMethod("GET")
                .withPath(config.getAuthorizePath())
        )
            .withId("oidc.authorize")
            .thenRespond(HttpClassCallback.callback(OidcAuthorizationCodeCallback.class.getName()));
    }

    private Expectation buildUserinfoExpectation(OidcProviderConfiguration config) {
        // A class callback because userinfo is an OAuth2 protected resource (OIDC Core §5.3): it must
        // require a bearer access token and return 401 when that token is missing or invalid. As a
        // static response it returned the subject and every configured claim to any caller without
        // looking at the Authorization header, so a test asserting "my app handles a 401 from userinfo"
        // could never fail.
        return new Expectation(
            request()
                .withMethod("GET")
                .withPath(config.getUserinfoPath())
        )
            .withId("oidc.userinfo")
            .thenRespond(HttpClassCallback.callback(OidcUserinfoCallback.class.getName()));
    }

    private Expectation buildIntrospectionExpectation(OidcProviderConfiguration config) {
        // A class callback so introspection validates the presented token (RFC 7662): a revoked token
        // is inactive; an opaque token is resolved by reference against what the minter recorded; a JWT
        // is verified against this provider's signing key and its validity window. Anything that does
        // not verify — garbage, an expired or tampered token, or one minted by a different provider —
        // is reported inactive, and an inactive response carries `active:false` and nothing else
        // (RFC 7662 §2.2). It never falls back to a static result.
        return new Expectation(
            request()
                .withMethod("POST")
                .withPath(config.getIntrospectPath())
        )
            .withId("oidc.introspect")
            .thenRespond(HttpClassCallback.callback(OidcIntrospectionCallback.class.getName()));
    }

    private Expectation buildDeviceAuthorizationExpectation(OidcProviderConfiguration config) {
        // A class callback so /device_authorization can mint a device_code + user_code per request
        // (RFC 8628 §3.2) and record them in the store for the token-endpoint polling exchange.
        return new Expectation(
            request()
                .withMethod("POST")
                .withPath(config.getDeviceAuthorizationPath())
        )
            .withId("oidc.deviceAuthorization")
            .thenRespond(HttpClassCallback.callback(OidcDeviceAuthorizationCallback.class.getName()));
    }

    private Expectation buildRevocationExpectation(OidcProviderConfiguration config) {
        // A class callback so revocation actually revokes (RFC 7009): the presented token is recorded
        // in the store so /introspect reports it inactive. A static 200 that did nothing meant a
        // revoked token still introspected as active.
        return new Expectation(
            request()
                .withMethod("POST")
                .withPath(config.getRevokePath())
        )
            .withId("oidc.revoke")
            .thenRespond(HttpClassCallback.callback(OidcRevocationCallback.class.getName()));
    }

    private Expectation buildLogoutExpectation() {
        // A class callback so /logout can honour an optional post_logout_redirect_uri (302) and
        // otherwise return a simple 200, mirroring an OIDC RP-initiated logout (end_session_endpoint).
        return new Expectation(
            request()
                .withMethod("GET")
                .withPath(LOGOUT_PATH)
        )
            .withId("oidc.logout")
            .thenRespond(HttpClassCallback.callback(OidcLogoutCallback.class.getName()));
    }

    private String serializeToJson(Object value) {
        try {
            return objectWriter.writeValueAsString(value);
        } catch (Exception e) {
            throw new RuntimeException("Failed to serialize OIDC response to JSON", e);
        }
    }
}
